# FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS packer
# WORKDIR /usr/src/boardgamegeekclient-packfase
# COPY . .
# RUN yarn pack 

# FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS esmtester
# ARG VERSION
# RUN echo "received: ${VERSION}"
# WORKDIR /usr/src/boardgamegeekclient-test
# COPY --from=packer /usr/src/boardgamegeekclient-packfase/boardgamegeekclient-v${VERSION}.tgz .
# COPY --from=packer /usr/src/boardgamegeekclient-packfase/buildtest/esm/ .
# RUN yarn add file:/usr/src/boardgamegeekclient-test/boardgamegeekclient-v${VERSION}.tgz && yarn
# ENV NODE_ENV production
# RUN adduser -D apprunneruser 
# USER apprunneruser
# CMD [ "yarn", "start" ]

FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS packer
WORKDIR /usr/src/boardgamegeekclient-packfase
COPY . .
RUN yarn pack

FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS compiler
WORKDIR /usr/src/boardgamegeekclient-compilerfase
COPY --from=packer /usr/src/boardgamegeekclient-packfase/test/unit/utils utils
COPY --from=packer /usr/src/boardgamegeekclient-packfase/buildtest/esm/ .
RUN yarn add global typescript && yarn add -D @types/node && npx tsc -p tsconfig.esm.json && mv utils/reflection/reflectionexport.json dist-utils/reflection/reflectionexport.json

FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS esmtester
ARG VERSION
RUN echo "received: ${VERSION}"
WORKDIR /usr/src/boardgamegeekclient-test
COPY --from=packer /usr/src/boardgamegeekclient-packfase/boardgamegeekclient-v${VERSION}.tgz .
COPY --from=compiler /usr/src/boardgamegeekclient-compilerfase/dist-utils dist-utils
COPY --from=compiler /usr/src/boardgamegeekclient-compilerfase/index.test.js .
COPY --from=compiler /usr/src/boardgamegeekclient-compilerfase/babel.config.js .
COPY --from=packer /usr/src/boardgamegeekclient-packfase/buildtest/esm/package.json .
RUN yarn
RUN yarn add file:/usr/src/boardgamegeekclient-test/boardgamegeekclient-v${VERSION}.tgz && yarn add jest
RUN adduser -D apprunneruser 
USER apprunneruser
CMD [ "yarn", "test" ]