# PeerDependencies are not installed by yarn.
# TsLib is not istalled and route to an error.
# TSDX build my lib with Tslib dependency.
FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS packer
WORKDIR /usr/src/boardgamegeekclient-packfase
COPY . .
RUN yarn pack 

FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS commmonjstester
WORKDIR /usr/src/boardgamegeekclient-test
COPY --from=packer /usr/src/boardgamegeekclient-packfase/boardgamegeekclient-v1.0.6.tgz .
COPY --from=packer /usr/src/boardgamegeekclient-packfase/examples/node/index.js .
RUN yarn init -y && yarn add file:/usr/src/boardgamegeekclient-test/boardgamegeekclient-v1.0.6.tgz && yarn add tslib -D
RUN adduser -D apprunneruser 
USER apprunneruser
CMD [ "node", "index.js" ]