FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS packer
WORKDIR /usr/src/boardgamegeekclient-packfase
COPY . .
RUN apk add nano
RUN yarn pack

FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS compiler
WORKDIR /usr/src/boardgamegeekclient-compilerfase
COPY --from=packer /usr/src/boardgamegeekclient-packfase/test/unit/utils utils
COPY --from=packer /usr/src/boardgamegeekclient-packfase/buildtest/cjs/ .
COPY --from=packer /usr/src/boardgamegeekclient-packfase/buildtest/tsconfig.test.json .
RUN yarn add global typescript jest && npx tsc -p tsconfig.test.json && mv utils/reflection/reflectionexport.json dist-utils/reflection/reflectionexport.json

FROM node:16-alpine@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b AS commmonjstester
WORKDIR /usr/src/boardgamegeekclient-test
COPY --from=packer /usr/src/boardgamegeekclient-packfase/boardgamegeekclient-v1.0.8.tgz .
COPY --from=compiler /usr/src/boardgamegeekclient-compilerfase/dist-utils dist-utils
COPY --from=compiler /usr/src/boardgamegeekclient-compilerfase/index.test.js .
COPY --from=compiler /usr/src/boardgamegeekclient-compilerfase/package.json .
ENV NODE_ENV production
RUN yarn add file:/usr/src/boardgamegeekclient-test/boardgamegeekclient-v1.0.8.tgz && yarn add jest
RUN adduser -D apprunneruser 
USER apprunneruser
CMD [ "yarn", "test" ]