### thing with all options

GET https://www.boardgamegeek.com/xmlapi2/thing?id=174430&comments=1&marketplace=1&pagesize=10&ratingcomments=1&stats=1&videos=1&type=boardgame&versions=1

### family with all options

GET https://www.boardgamegeek.com/xmlapi2/family?id=8374&type=boardgamefamily

### collection

GET https://www.boardgamegeek.com/xmlapi2/collection?username=mattiabanned HTTP/1.1

### plays

GET https://www.boardgamegeek.com/xmlapi2/plays?username=mattiabanned HTTP/1.1

### thread

GET https://www.boardgamegeek.com/xmlapi2/thread?id=1082079 HTTP/1.1

### search

GET https://www.boardgamegeek.com/xmlapi2/search?query=34294&type=boardgame

### search

GET https://www.boardgamegeek.com/xmlapi2/search?query=gloom&type=boardgame

### search

GET https://www.boardgamegeek.com/xmlapi2/search?query=gloom

### hot

GET https://www.boardgamegeek.com/xmlapi2/hot?type=boardgame
